include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

build:
  stage: build
  script:
    - echo "Running RTL build..."
    - source /projects/sim-gitlab
    - cd /projects/spandex-gitlab/socs/xilinx-vc707-xc7vx485t
    - git checkout $CI_COMMIT_BRANCH
    - git pull origin $CI_COMMIT_BRANCH
    - make l2-distclean l2-hls l2_denovo-distclean l2_denovo-hls llc-distclean llc-hls
    - source /projects/sim-gitlab
    - rm -rf xcelium/
    - make xmsim-compile soft-distclean soft sort-barec
    - echo "PASS"

test-systest:
  stage: test
  script:
    - make soft
    - echo "Running simulation..."
    - rm -f /projects/simout.txt
    - cd /projects/spandex-gitlab/socs/xilinx-vc707-xc7vx485t
    - source /projects/sim-gitlab
    - printf "run\nexit\n" | make xmsim
    - echo "PASS"

deploy:
  stage: deploy
  script:
    - echo "PASS"
