include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

build:
  stage: build
  script:
    - echo "Running RTL build..."
    - source /projects/sim-gitlab
    - source /projects/hls-gitlab
    - cd /projects/spandex-gitlab/socs/xilinx-vc707-xc7vx485t
    - git checkout $CI_COMMIT_BRANCH
    - git pull origin $CI_COMMIT_BRANCH
    - git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA | grep systemc || exit_code=$?
    - if [ $exit_code -ne 0 ]; then echo "Skipping SystemC builds..."; fi;
    - if [ $exit_code -eq 0 ]; then make l2-distclean l2-hls l2_denovo-distclean l2_denovo-hls llc-distclean llc-hls; fi;
    - source /projects/sim-gitlab
    - rm -rf xcelium/
    - make xmsim-compile
    - echo "PASS"

test-sort-baseline:
  stage: test
  script:
    - echo "Generating ESP configs..."
    - cd /projects/spandex-gitlab/socs/xilinx-vc707-xc7vx485t
    - make esp-config-distclean
    - cp /projects/.esp_config-sort ./esp_config
    - make esp-config
    - printf "run\nexit\n" | make xmsim
    - python3 check.py sort-gold.txt
    - echo "PASS"

deploy:
  stage: deploy
  script:
    - echo "PASS"
