build:
  stage: build
  script:
    - echo "Running RTL build..."
    - source /projects/sim-gitlab
    - source /projects/hls-gitlab
    - cd /projects/spandex-gitlab/socs/xilinx-vc707-xc7vx485t
    - git checkout $CI_COMMIT_BRANCH
    - make l2-distclean
    - make l2-hls
    - make l2_denovo-distclean
    - make l2_denovo-hls
    - make llc-distclean
    - make llc-hls
    - source /projects/sim-gitlab
    - rm -rf xcelium/
    - make xmsim-compile
    - echo "PASS"

test-sort-baseline:
  stage: test
  script:
    - echo "This job tests something"

deploy:
  stage: deploy
  script:
    - echo "PASS"
